spring:
  datasource:
    url: jdbc:postgresql://192.168.0.31:5432/challenge
    username: challenge
    password: challenge1123!

hbase:
  zookeeper:
    quorum: devchallenge01.e4motion.com,devchallenge02.e4motion.com,devchallenge03.e4motion.com
    property:
      clientPort: 2181

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG