apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-monitor
  template:
    metadata:
      labels:
        app: challenge-monitor
#      annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/path: /metrics
#        prometheus.io/port: "9113"
    spec:
      containers:
      - name: challenge-monitor
        image: registry.emgglobal.co.kr:9443/challenge-monitor:2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
#        resources:
#          requests:
#            memory: 512Mi
#          limits:
#            memory: 4Gi
#      - name: nginx-exporter
#        image: nginx/nginx-prometheus-exporter
#        env:
#        - name: SCRAPE_URI
#          value: http://localhost:8090/metrics
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-monitor
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.11
  selector:
    app: challenge-monitor
  ports:
    - port: 80
      targetPort: 8090
