spring:
  datasource:
    url: jdbc:postgresql://125.143.64.233:31432/challenge
    username: challenge
    password: challenge1123!

hbase:
  zookeeper:
    quorum: challenge.data01.e4motion.com,challenge.data02.e4motion.com,challenge.data03.e4motion.com
    property:
      clientPort: 2181

challenge-api:
  url: http://192.168.0.12:8091/v2/camera/

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG