spring:
  datasource:
    url: jdbc:postgresql://192.168.0.31:5432/challenge
    username: challenge
    password: challenge123!

hbase:
  zookeeper:
    quorum: 192.168.0.41,192.168.0.42,192.168.0.43
    property:
      clientPort: 2181

challenge-api:
  url: http://192.168.0.12:8091/v2/camera/

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG