spring:
  datasource:
    url: jdbc:postgresql://192.168.0.231:5432/challenge2022
    username: challenge
    password: challenge1123!

hbase:
  zookeeper:
    quorum: devchallenge01.e4motion.com,devchallenge02.e4motion.com,devchallenge03.e4motion.com
    property:
      clientPort: 2181

challenge-api:
  url: http://192.168.0.251:8091/v2/camera/

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
