server:
  port: 8092
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/challenge2022
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties: 
      format_sql: true
    show-sql: true
    open-in-view: false

hbase:
  zookeeper:
    quorum: devchallenge01.e4motion.com,devchallenge02.e4motion.com,devchallenge03.e4motion.com
    property:
      clientPort: 2181

jwt:
  secret: jwt secret smart city challenge
  token-validity-in-seconds: 86400

challenge-api:
  url: http://devchallenge01.e4motion.com:8091/v2/camera/

cors:
  origins: >
    http://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    info:
      title: Challenge Data Collector API
      description: REST API for Challenge Data Collector
      version: 2.0.0
    syntaxHighlight:                # because of ui performance
      activated: false

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
