apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-data-collector
  template:
    metadata:
      labels:
        app: challenge-data-collector
    spec:
      containers:
      - name: challenge-data-collector
        image: 192.168.0.240:5000/challenge-data-collector:0.0.1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
        ports:
        - containerPort: 8092
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 4Gi
      hostAliases:
      - ip: 192.168.0.231
        hostnames:
        - devchallenge01.e4motion.com
        - devchallenge01
      - ip: 192.168.0.232
        hostnames:
        - devchallenge02.e4motion.com
        - devchallenge02
      - ip: 192.168.0.233
        hostnames:
        - devchallenge03.e4motion.com
        - devchallenge03  
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-data-collector
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  selector:
    app: challenge-data-collector
  ports:
    - port: 8092
      targetPort: 8092
