apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-api
  template:
    metadata:
      labels:
        app: challenge-api
    spec:
      containers:
      - name: challenge-api
        image: 192.168.0.240:5000/challenge-api:0.0.1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 2Gi
#        volumeMounts:
#        - mountPath: /logs
#          name: host-path
#      volumes:
#      - name: host-path
#        hostPath:
#          path: /var/log/challenge-api
#          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-api
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.251
  selector:
    app: challenge-api
  ports:
    - port: 8081
      targetPort: 8081
