apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-data-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-data-provider
  template:
    metadata:
      labels:
        app: challenge-data-provider
    spec:
      containers:
      - name: challenge-data-provider
        image: registry.emgglobal.co.kr:9443/challenge-data-provider:2.0.0
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
        ports:
        - containerPort: 8093
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 4Gi
      hostAliases:
      - ip: 192.168.0.231
        hostnames:
        - devchallenge01.e4motion.com
        - devchallenge01
      - ip: 192.168.0.232
        hostnames:
        - devchallenge02.e4motion.com
        - devchallenge02
      - ip: 192.168.0.233
        hostnames:
        - devchallenge03.e4motion.com
        - devchallenge03  
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-data-provider
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.253
  selector:
    app: challenge-data-provider
  ports:
    - port: 8093
      targetPort: 8093
