apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challenge-monitor
  template:
    metadata:
      labels:
        app: challenge-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9113"
    spec:
      containers:
      - name: challenge-monitor
        image: 192.168.0.241:5000/challenge-monitor:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter
        env:
        - name: SCRAPE_URI
          value: http://localhost:8080/metrics
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-monitor
spec:
  type: LoadBalancer
  selector:
    app: challenge-monitor
  ports:
    - port: 8080
      targetPort: 8080
