# unittest
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: SA
    password:
    initialization-mode: always # should be always - We want to insert data for testing using data-h2.sql
    data: classpath:data-h2.sql

  jpa:
    hibernate: 
      ddl-auto: create-drop     # should be create... - We want to make tables using Entity classes.
    defer-datasource-initialization: true
