spring:
  datasource:
    url: jdbc:postgresql://192.168.0.231:5432/challenge2022
    username: challenge
    password: challenge123!

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG