server:
  port: 8091
  tomcat:
    max-swallow-size: 100MB         # to catch file size exceed exception in spring.
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/challenge2022
    username: postgres
    password: postgres

  sql:
    init:
      platform: postgresql
      mode: never                   # never, always
      encoding: UTF-8

  jpa:
    database-platform: com.e4motion.challenge.common.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none                # none, create, update, create-drop
    defer-datasource-initialization: true
    properties: 
      format_sql: true
    show-sql: false
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 50MB

jwt:
  header: Authorization
  secret: jwt secret smart city challenge
  token-validity-in-seconds: 86400

cors:
  origins: >
    http://localhost:3000,
    http://192.168.0.17:3000,
    http://192.168.1.3:3000,
    http://192.168.0.68:3000,
    http://192.168.0.231:8090,
    http://192.168.0.250:8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    info:
      title: Challenge API
      description: REST API for Challenge
      version: 1.0.0
    syntaxHighlight:                # because of performance
      activated: false

logging:
  level:
    root: INFO
    web: DEBUG
    com.e4motion: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
